"""Utilities for the Planner node."""

from __future__ import annotations

from typing import Any

from odr.agents.types import WorkerTask
from .contracts import ResearchPlan


def plan_to_worker_tasks(plan: ResearchPlan, raw_context: str) -> list[WorkerTask]:
    """Convert a structured plan into WorkerTask TypedDicts.
    
    DATA FLOW (where task fields come from):
    - plan.tasks[*].task_description → WorkerTask["task_description"]
                                      ↑ Usually: generated by choose_workers LLM (nodes.py)
    - plan.tasks[*].deliverables     → WorkerTask["deliverables"] + appended to context
                                      ↑ Usually: generated by choose_workers LLM (nodes.py)
    - plan.tasks[*].requirements     → WorkerTask["requirements"] (merged with runtime knobs)
                                      ↑ Usually: generated by choose_workers LLM (nodes.py)
    - plan.tasks[*].runtime          → merged into WorkerTask["requirements"]
                                      ↑ Usually: set by choose_workers based on iteration/mode
    """
    tasks: list[WorkerTask] = []
    for idx, t in enumerate(plan.tasks, start=1):
        deliverables_txt = ""
        if t.deliverables:
            deliverables_txt = "\nDeliverables:\n- " + "\n- ".join(t.deliverables)
        req_txt = (
            f"\nEvidence requirements:\n- urls_required={t.requirements.urls_required}\n"
            f"- min_unique_urls={t.requirements.min_unique_urls}"
        )
        req_payload: dict[str, Any] = dict(t.requirements.model_dump())
        # Merge runtime knobs into requirements so workers can read them from a single place.
        # This also supports backward compatibility with existing WorkerTask contracts.
        if isinstance(t.runtime, dict):
            for k, v in t.runtime.items():
                req_payload[k] = v
        tasks.append(
            WorkerTask(
                worker_id=t.worker_id or f"worker_{idx}",
                task_description=t.task_description,
                context=(raw_context + deliverables_txt + req_txt).strip(),
                worker_type=t.worker_type.value,
                deliverables=list(t.deliverables),
                requirements=req_payload,
            )
        )
    return tasks



